apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
data:
   id_rsa: <base64 encoded value> 
   known_hosts: <base64 encoded value>
   config: SG9zdCBnaXRodWIuY29tCkhvc3RuYW1lIHNzaC5naXRodWIuY29tClBvcnQgNDQzClVzZXIgZ2l0Cg==
