---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-actions-account
  namespace: tekton-poc
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-actions-role
rules:
  # Core API
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  # Apps API
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  # Tekton API
  - apiGroups: ["tekton.dev"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-actions-binding
subjects:
  - kind: ServiceAccount
    name: kubernetes-actions-account
    namespace: tekton-poc
roleRef:
  kind: ClusterRole
  name: kubernetes-actions-role
  apiGroup: rbac.authorization.k8s.io
